### ISSUE TITLE
#1 First Issue

### ISSUE THREAD

**Issue by adityarev** [2019-pemrogramanberbasiskerangkakerja-h/secure-gate-system-duh-purnomo-_#1]
Response Issues:
- Login, tidak ada message error. Ketika atribut value sudah berubah, dan dicoba login kembali, tidak ada perubahan response

Convention Issues:
- GET User info, perbaiki jadi endpoint /users/:id (Bukan nrp)
- POST User, perbaiki jadi endpoint /users
- PUT User, perbaiki jadi endpoint /users
- DELETE User, perbaiki jadi endpoint /users/:id (Bukan nrp)

- GET Gate info, perbaiki jadi endpoint /gates/:id (Bukan nama gate)
- POST Gate perbaiki jadi endpoint /gates
- PUT Gate , perbaiki jadi endpoint /gates
- DELETE Gate , perbaiki jadi endpoint /gates/:id (Bukan nama gate)

- GET Group info, perbaiki jadi endpoint /groups/:id (Bukan nama group)
- POST Group, perbaiki jadi endpoint /groups
- PUT Group, perbaiki jadi endpoint /groups
- DELETE Group, perbaiki jadi endpoint /groups/:id (Bukan nama group)

Overall, semua API sudah bisa diakses dan response yang diberikan sudah benar

**Comment by mailsyarief** [comment]
👍
